Fix mkdir -p error

diff --git a/overlay/usr/local/bin/generate_letsencrypt_certificates b/overlay/usr/local/bin/generate_letsencrypt_certificates
--- a/overlay/usr/local/bin/generate_letsencrypt_certificates
+++ b/overlay/usr/local/bin/generate_letsencrypt_certificates
@@ -22,6 +22,11 @@ fi
 # Move self-signed certificates
 tmp_backup="/tmp/$(openssl rand --hex 8)"
 mkdir --parent "$tmp_backup"
+if [ $? -eq 64 ]
+        mkdir -p "$tmp_backup"
+else
+        echo "Unable to create certificate backup" >&2
+fi
 mv /usr/local/etc/letsencrypt/live/truenas "$tmp_backup"
 echo "Old certificates moved to: $tmp_backup"
 
